services:
  - type: web
    name: mancy-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 12100
    healthCheckPath: /health
    autoDeploy: true
